const wa="https://wa.me/";
export default function Home(){return <main>
<header><b>MK CARS</b><a href="#reservar">RESERVAR</a></header>
<section className="hero"><div className="eyebrow">CAR WASH PREMIUM · A DOMICILIO</div><h1>Tu auto impecable.<br/><span>Sin moverte.</span></h1><p>Llevamos una experiencia de lavado premium hasta tu casa u oficina en Gran Mendoza.</p><div className="actions"><a className="primary" href="#reservar">Reservar lavado</a><a className="secondary" href="#servicios">Ver servicios</a></div><div className="trust"><span>✓ Vamos a tu ubicación</span><span>✓ Agua propia o del domicilio</span><span>✓ 9:00 a 18:00</span></div></section>
<section id="servicios"><div className="eyebrow">SERVICIOS</div><h2>Elegí el lavado ideal</h2><p className="lead">El valor final depende del tipo de vehículo y servicio elegido.</p><div className="cards"><article><small>DESDE</small><h3>$25.000</h3><p>Autos</p><span>Lavado premium a domicilio</span></article><article className="featured"><small>PREMIUM</small><h3>$30.000</h3><p>SUV</p><span>Mayor tamaño, mismo nivel de detalle</span></article><article><small>HASTA</small><h3>$35.000</h3><p>Pick-ups</p><span>Servicio adaptado a vehículos grandes</span></article></div></section>
<section className="dark"><div className="eyebrow">CÓMO FUNCIONA</div><h2>Simple. Nosotros vamos.</h2><div className="steps"><div><b>01</b><h3>Reservá</h3><p>Coordiná tu turno por WhatsApp.</p></div><div><b>02</b><h3>Compartí tu ubicación</h3><p>Validamos cobertura dentro de Gran Mendoza.</p></div><div><b>03</b><h3>Disfrutá</h3><p>Lavamos tu vehículo donde estés.</p></div></div></section>
<section><div className="eyebrow">COBERTURA</div><h2>Gran Mendoza</h2><p className="lead">Capital, Godoy Cruz, Luján de Cuyo, Guaymallén y Las Heras. Compartinos tu ubicación y confirmamos disponibilidad.</p><a className="secondary" href="#reservar">Consultar mi ubicación</a></section>
<section id="reservar" className="cta"><div><div className="eyebrow">RESERVAS</div><h2>Tu auto puede quedar impecable hoy.</h2><p>Escribinos y coordinamos ubicación, vehículo y horario.</p></div><a className="primary light" href={wa}>Reservar por WhatsApp</a></section>
<footer><b>MK CARS</b><span>Car Wash Premium · Mendoza</span><span>9:00 — 18:00</span></footer>
</main>}